-- Generated by packages/db/seed/generate.ts from seed/catalogue.ts. Do not edit by hand.
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('checkers', 'Checkers', 'major', 'xtra_savings');
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('shoprite', 'Shoprite', 'major', 'xtra_savings');
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('usave', 'Usave', 'major', NULL);
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('pick-n-pay', 'Pick n Pay', 'major', 'smart_shopper');
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('boxer', 'Boxer', 'major', NULL);
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('woolworths', 'Woolworths', 'major', 'wrewards');
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('spar', 'Spar', 'major', 'spar_rewards');
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('ok-foods', 'OK Foods', 'major', NULL);
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('food-lovers', 'Food Lover''s Market', 'major', NULL);
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('makro', 'Makro', 'major', NULL);
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('cambridge', 'Cambridge Food', 'regional', NULL);
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('choppies', 'Choppies', 'regional', NULL);
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('save-hyper', 'Save Hyper', 'regional', NULL);
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('independent', 'Independent supermarket', 'informal', NULL);
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('spaza', 'Spaza shop', 'informal', NULL);
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('butchery', 'Butchery', 'informal', NULL);
--> statement-breakpoint
INSERT INTO chains (id, name, tier, loyalty_program) VALUES ('fruit-veg', 'Fruit & veg stall', 'informal', NULL);
--> statement-breakpoint
INSERT INTO categories (id, name, sort) VALUES ('fruit-veg', 'Fruit & veg', 1);
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('potatoes', 'fruit-veg', 'Potatoes', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('onions', 'fruit-veg', 'Onions', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('tomatoes', 'fruit-veg', 'Tomatoes', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('cabbage', 'fruit-veg', 'Cabbage', 'each');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('carrots', 'fruit-veg', 'Carrots', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('spinach', 'fruit-veg', 'Spinach', 'each');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('bananas', 'fruit-veg', 'Bananas', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('apples', 'fruit-veg', 'Apples', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('oranges', 'fruit-veg', 'Oranges', 'g');
--> statement-breakpoint
INSERT INTO categories (id, name, sort) VALUES ('meat', 'Meat, chicken & fish', 2);
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('whole-chicken', 'meat', 'Whole chicken', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('chicken-portions', 'meat', 'Chicken portions', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('beef-mince', 'meat', 'Beef mince', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('stewing-beef', 'meat', 'Stewing beef', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('boerewors', 'meat', 'Boerewors', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('pork-chops', 'meat', 'Pork chops', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('polony', 'meat', 'Polony', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('viennas', 'meat', 'Viennas', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('frozen-fish', 'meat', 'Frozen fish', 'g');
--> statement-breakpoint
INSERT INTO categories (id, name, sort) VALUES ('dairy', 'Dairy & eggs', 3);
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('fresh-milk', 'dairy', 'Fresh milk', 'ml');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('long-life-milk', 'dairy', 'Long-life milk', 'ml');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('amasi', 'dairy', 'Amasi', 'ml');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('yoghurt', 'dairy', 'Yoghurt', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('cheese', 'dairy', 'Cheese', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('butter', 'dairy', 'Butter', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('eggs', 'dairy', 'Eggs', 'each');
--> statement-breakpoint
INSERT INTO categories (id, name, sort) VALUES ('bakery', 'Bakery', 4);
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('white-bread', 'bakery', 'White bread', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('brown-bread', 'bakery', 'Brown bread', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('bread-rolls', 'bakery', 'Bread rolls', 'each');
--> statement-breakpoint
INSERT INTO categories (id, name, sort) VALUES ('staples', 'Maize meal, rice & grains', 5);
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('maize-meal', 'staples', 'Maize meal', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('rice', 'staples', 'Rice', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('samp', 'staples', 'Samp', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('dried-beans', 'staples', 'Dried beans', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('pasta', 'staples', 'Pasta', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('oats', 'staples', 'Oats', 'g');
--> statement-breakpoint
INSERT INTO categories (id, name, sort) VALUES ('baking', 'Baking & sugar', 6);
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('white-sugar', 'baking', 'White sugar', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('brown-sugar', 'baking', 'Brown sugar', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('cake-flour', 'baking', 'Cake flour', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('bread-flour', 'baking', 'Bread flour', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('yeast', 'baking', 'Yeast', 'g');
--> statement-breakpoint
INSERT INTO categories (id, name, sort) VALUES ('oils-spreads', 'Oils & spreads', 7);
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('cooking-oil', 'oils-spreads', 'Cooking oil', 'ml');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('margarine', 'oils-spreads', 'Margarine', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('peanut-butter', 'oils-spreads', 'Peanut butter', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('jam', 'oils-spreads', 'Jam', 'g');
--> statement-breakpoint
INSERT INTO categories (id, name, sort) VALUES ('tins-sauces', 'Tins, sauces & spices', 8);
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('baked-beans', 'tins-sauces', 'Baked beans', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('pilchards', 'tins-sauces', 'Pilchards', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('chakalaka', 'tins-sauces', 'Chakalaka', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('tomato-sauce', 'tins-sauces', 'Tomato sauce', 'ml');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('mayonnaise', 'tins-sauces', 'Mayonnaise', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('curry-powder', 'tins-sauces', 'Curry powder', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('seasoning', 'tins-sauces', 'Seasoning', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('stock-cubes', 'tins-sauces', 'Stock cubes', 'each');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('soup-powder', 'tins-sauces', 'Soup powder', 'g');
--> statement-breakpoint
INSERT INTO categories (id, name, sort) VALUES ('breakfast', 'Breakfast', 9);
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('cereal', 'breakfast', 'Cereal', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('instant-porridge', 'breakfast', 'Instant porridge', 'g');
--> statement-breakpoint
INSERT INTO categories (id, name, sort) VALUES ('drinks', 'Drinks', 10);
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('tea', 'drinks', 'Tea', 'each');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('coffee', 'drinks', 'Coffee', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('soft-drinks', 'drinks', 'Soft drinks', 'ml');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('fruit-juice', 'drinks', 'Fruit juice', 'ml');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('cordial', 'drinks', 'Cordial', 'ml');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('bottled-water', 'drinks', 'Bottled water', 'ml');
--> statement-breakpoint
INSERT INTO categories (id, name, sort) VALUES ('snacks', 'Snacks & sweets', 11);
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('chips', 'snacks', 'Chips', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('biscuits', 'snacks', 'Biscuits', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('chocolate', 'snacks', 'Chocolate', 'g');
--> statement-breakpoint
INSERT INTO categories (id, name, sort) VALUES ('frozen', 'Frozen', 12);
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('frozen-veg', 'frozen', 'Frozen vegetables', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('frozen-chips', 'frozen', 'Frozen chips', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('ice-cream', 'frozen', 'Ice cream', 'ml');
--> statement-breakpoint
INSERT INTO categories (id, name, sort) VALUES ('cleaning', 'Cleaning & laundry', 13);
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('dishwashing-liquid', 'cleaning', 'Dishwashing liquid', 'ml');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('washing-powder', 'cleaning', 'Washing powder', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('bleach', 'cleaning', 'Bleach', 'ml');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('surface-cleaner', 'cleaning', 'Surface cleaner', 'ml');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('toilet-paper', 'cleaning', 'Toilet paper', 'each');
--> statement-breakpoint
INSERT INTO categories (id, name, sort) VALUES ('personal-care', 'Toiletries', 14);
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('toothpaste', 'personal-care', 'Toothpaste', 'ml');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('bath-soap', 'personal-care', 'Bath soap', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('petroleum-jelly', 'personal-care', 'Petroleum jelly', 'ml');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('deodorant', 'personal-care', 'Deodorant', 'ml');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('sanitary-pads', 'personal-care', 'Sanitary pads', 'each');
--> statement-breakpoint
INSERT INTO categories (id, name, sort) VALUES ('baby', 'Baby', 15);
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('nappies', 'baby', 'Nappies', 'each');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('baby-formula', 'baby', 'Baby formula', 'g');
--> statement-breakpoint
INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES ('baby-wipes', 'baby', 'Baby wipes', 'each');
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-potatoes-1x7000g', 'potatoes', 'Potatoes', NULL, 7000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-onions-1x2000g', 'onions', 'Onions', NULL, 2000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-tomatoes-per-kg', 'tomatoes', 'Tomatoes', NULL, 1000, 'g', 1, 1, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-cabbage-1x1each', 'cabbage', 'Cabbage', NULL, 1, 'each', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-carrots-1x1000g', 'carrots', 'Carrots', NULL, 1000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-bananas-per-kg', 'bananas', 'Bananas', NULL, 1000, 'g', 1, 1, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-apples-1x1500g', 'apples', 'Apples', NULL, 1500, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-whole-fresh-chicken-per-kg', 'whole-chicken', 'Whole fresh chicken', NULL, 1000, 'g', 1, 1, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-beef-mince-per-kg', 'beef-mince', 'Beef mince', NULL, 1000, 'g', 1, 1, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-beef-stewing-pieces-per-kg', 'stewing-beef', 'Beef stewing pieces', NULL, 1000, 'g', 1, 1, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-boerewors-per-kg', 'boerewors', 'Boerewors', NULL, 1000, 'g', 1, 1, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-pork-loin-chops-per-kg', 'pork-chops', 'Pork loin chops', NULL, 1000, 'g', 1, 1, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-rainbow-iqf-chicken-mixed-portions-1x2000g', 'chicken-portions', 'IQF Chicken Mixed Portions', 'Rainbow', 2000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-large-eggs-1x30each', 'eggs', 'Large eggs', NULL, 30, 'each', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-nulaid-large-eggs-1x18each', 'eggs', 'Large Eggs', 'Nulaid', 18, 'each', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-clover-full-cream-fresh-milk-1x2000ml', 'fresh-milk', 'Full Cream Fresh Milk', 'Clover', 2000, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-clover-low-fat-fresh-milk-1x2000ml', 'fresh-milk', 'Low Fat Fresh Milk', 'Clover', 2000, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-parmalat-full-cream-fresh-milk-1x2000ml', 'fresh-milk', 'Full Cream Fresh Milk', 'Parmalat', 2000, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-clover-full-cream-long-life-milk-1x1000ml', 'long-life-milk', 'Full Cream Long Life Milk', 'Clover', 1000, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-parmalat-full-cream-long-life-milk-6x1000ml', 'long-life-milk', 'Full Cream Long Life Milk', 'Parmalat', 1000, 'ml', 6, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-inkomazi-amasi-1x2000ml', 'amasi', 'Amasi', 'Inkomazi', 2000, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-clover-salted-butter-1x500g', 'butter', 'Salted Butter', 'Clover', 500, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-albany-superior-white-bread-1x700g', 'white-bread', 'Superior White Bread', 'Albany', 700, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-sasko-premium-white-bread-1x700g', 'white-bread', 'Premium White Bread', 'Sasko', 700, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-blue-ribbon-classic-white-bread-1x700g', 'white-bread', 'Classic White Bread', 'Blue Ribbon', 700, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-albany-superior-brown-bread-1x700g', 'brown-bread', 'Superior Brown Bread', 'Albany', 700, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-sasko-premium-brown-bread-1x700g', 'brown-bread', 'Premium Brown Bread', 'Sasko', 700, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-white-star-super-maize-meal-1x10000g', 'maize-meal', 'Super Maize Meal', 'White Star', 10000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-white-star-super-maize-meal-1x5000g', 'maize-meal', 'Super Maize Meal', 'White Star', 5000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-white-star-super-maize-meal-1x2500g', 'maize-meal', 'Super Maize Meal', 'White Star', 2500, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-iwisa-super-maize-meal-1x10000g', 'maize-meal', 'Super Maize Meal', 'Iwisa', 10000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-iwisa-super-maize-meal-1x5000g', 'maize-meal', 'Super Maize Meal', 'Iwisa', 5000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-ace-super-maize-meal-1x10000g', 'maize-meal', 'Super Maize Meal', 'Ace', 10000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-tastic-long-grain-parboiled-rice-1x2000g', 'rice', 'Long Grain Parboiled Rice', 'Tastic', 2000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-tastic-long-grain-parboiled-rice-1x1000g', 'rice', 'Long Grain Parboiled Rice', 'Tastic', 1000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-spekko-long-grain-parboiled-rice-1x2000g', 'rice', 'Long Grain Parboiled Rice', 'Spekko', 2000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-fatti-s-and-moni-s-spaghetti-1x500g', 'pasta', 'Spaghetti', 'Fatti''s & Moni''s', 500, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-fatti-s-and-moni-s-macaroni-1x500g', 'pasta', 'Macaroni', 'Fatti''s & Moni''s', 500, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-jungle-oats-1x1000g', 'oats', 'Oats', 'Jungle', 1000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-huletts-white-sugar-1x2500g', 'white-sugar', 'White Sugar', 'Huletts', 2500, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-selati-white-sugar-1x2500g', 'white-sugar', 'White Sugar', 'Selati', 2500, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-snowflake-cake-wheat-flour-1x2500g', 'cake-flour', 'Cake Wheat Flour', 'Snowflake', 2500, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-golden-cloud-cake-wheat-flour-1x2500g', 'cake-flour', 'Cake Wheat Flour', 'Golden Cloud', 2500, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-snowflake-white-bread-wheat-flour-1x2500g', 'bread-flour', 'White Bread Wheat Flour', 'Snowflake', 2500, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-sunfoil-sunflower-oil-1x2000ml', 'cooking-oil', 'Sunflower Oil', 'Sunfoil', 2000, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-sunfoil-sunflower-oil-1x750ml', 'cooking-oil', 'Sunflower Oil', 'Sunfoil', 750, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-excella-sunflower-oil-1x2000ml', 'cooking-oil', 'Sunflower Oil', 'Excella', 2000, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-rama-original-spread-1x500g', 'margarine', 'Original Spread', 'Rama', 500, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-stork-bake-1x500g', 'margarine', 'Bake', 'Stork', 500, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-black-cat-smooth-peanut-butter-1x400g', 'peanut-butter', 'Smooth Peanut Butter', 'Black Cat', 400, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-all-gold-apricot-jam-1x450g', 'jam', 'Apricot Jam', 'All Gold', 450, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-koo-baked-beans-in-tomato-sauce-1x410g', 'baked-beans', 'Baked Beans in Tomato Sauce', 'Koo', 410, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-lucky-star-pilchards-in-tomato-sauce-1x400g', 'pilchards', 'Pilchards in Tomato Sauce', 'Lucky Star', 400, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-koo-chakalaka-mild-and-spicy-1x410g', 'chakalaka', 'Chakalaka Mild & Spicy', 'Koo', 410, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-all-gold-tomato-sauce-1x700ml', 'tomato-sauce', 'Tomato Sauce', 'All Gold', 700, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-crosse-and-blackwell-tangy-mayonnaise-1x750g', 'mayonnaise', 'Tangy Mayonnaise', 'Crosse & Blackwell', 750, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-rajah-mild-and-spicy-curry-powder-1x100g', 'curry-powder', 'Mild & Spicy Curry Powder', 'Rajah', 100, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-knorr-aromat-original-1x75g', 'seasoning', 'Aromat Original', 'Knorr', 75, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-bokomo-weet-bix-1x900g', 'cereal', 'Weet-Bix', 'Bokomo', 900, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-ace-instant-porridge-original-1x1000g', 'instant-porridge', 'Instant Porridge Original', 'Ace', 1000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-joko-tagless-tea-bags-1x100each', 'tea', 'Tagless Tea Bags', 'Joko', 100, 'each', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-freshpak-rooibos-tea-bags-1x80each', 'tea', 'Rooibos Tea Bags', 'Freshpak', 80, 'each', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-nestle-ricoffy-1x750g', 'coffee', 'Ricoffy', 'Nestlé', 750, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-nescafe-classic-instant-coffee-1x200g', 'coffee', 'Classic Instant Coffee', 'Nescafé', 200, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-coca-cola-original-1x2000ml', 'soft-drinks', 'Original', 'Coca-Cola', 2000, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-sprite-lemon-lime-1x2000ml', 'soft-drinks', 'Lemon-Lime', 'Sprite', 2000, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-fanta-orange-1x2000ml', 'soft-drinks', 'Orange', 'Fanta', 2000, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-ceres-medley-of-fruits-juice-1x1000ml', 'fruit-juice', 'Medley of Fruits Juice', 'Ceres', 1000, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-oros-orange-squash-1x2000ml', 'cordial', 'Orange Squash', 'Oros', 2000, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-valpre-still-water-1x5000ml', 'bottled-water', 'Still Water', 'Valpré', 5000, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-simba-salt-and-vinegar-chips-1x120g', 'chips', 'Salt & Vinegar Chips', 'Simba', 120, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-bakers-tennis-biscuits-1x200g', 'biscuits', 'Tennis Biscuits', 'Bakers', 200, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-bakers-eet-sum-mor-1x200g', 'biscuits', 'Eet-Sum-Mor', 'Bakers', 200, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-cadbury-dairy-milk-1x80g', 'chocolate', 'Dairy Milk', 'Cadbury', 80, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-mccain-mixed-vegetables-1x1000g', 'frozen-veg', 'Mixed Vegetables', 'McCain', 1000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-ola-rich-n-creamy-vanilla-1x2000ml', 'ice-cream', 'Rich ''n Creamy Vanilla', 'Ola', 2000, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-sunlight-dishwashing-liquid-regular-1x750ml', 'dishwashing-liquid', 'Dishwashing Liquid Regular', 'Sunlight', 750, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-omo-auto-washing-powder-1x2000g', 'washing-powder', 'Auto Washing Powder', 'OMO', 2000, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-jik-regular-bleach-1x750ml', 'bleach', 'Regular Bleach', 'Jik', 750, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-handy-andy-lemon-fresh-cream-cleaner-1x750ml', 'surface-cleaner', 'Lemon Fresh Cream Cleaner', 'Handy Andy', 750, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-twinsaver-2-ply-toilet-paper-9x1each', 'toilet-paper', '2-Ply Toilet Paper', 'Twinsaver', 1, 'each', 9, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-colgate-regular-toothpaste-1x100ml', 'toothpaste', 'Regular Toothpaste', 'Colgate', 100, 'ml', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-lifebuoy-total-10-soap-1x175g', 'bath-soap', 'Total 10 Soap', 'Lifebuoy', 175, 'g', 1, 0, 0, 0);
--> statement-breakpoint
INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES ('seed-vaseline-blue-seal-petroleum-jelly-1x250ml', 'petroleum-jelly', 'Blue Seal Petroleum Jelly', 'Vaseline', 250, 'ml', 1, 0, 0, 0);
