// Writes migrations/0005_seed_catalogue.sql from seed/catalogue.ts.
// Run with `pnpm db:seed:generate`; commit the generated SQL.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { categories, chains, products } from './catalogue.ts';

const sql = (v: string | number | boolean | null): string => {
  if (v === null) return 'NULL';
  if (typeof v === 'boolean') return v ? '1' : '0';
  if (typeof v === 'number') return String(v);
  return `'${v.replaceAll("'", "''")}'`;
};

const slug = (s: string) =>
  s
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

const typeIds = new Set(categories.flatMap(([, , types]) => types.map(([id]) => id)));
const lines: string[] = [
  '-- Generated by packages/db/seed/generate.ts from seed/catalogue.ts. Do not edit by hand.',
];

for (const [id, name, tier, loyalty] of chains) {
  lines.push(
    `INSERT INTO chains (id, name, tier, loyalty_program) VALUES (${[id, name, tier, loyalty].map(sql).join(', ')});`,
  );
}

categories.forEach(([id, name, types], i) => {
  lines.push(
    `INSERT INTO categories (id, name, sort) VALUES (${sql(id)}, ${sql(name)}, ${i + 1});`,
  );
  for (const [typeId, typeName, unit] of types) {
    lines.push(
      `INSERT INTO product_types (id, category_id, name, default_size_unit) VALUES (${[typeId, id, typeName, unit].map(sql).join(', ')});`,
    );
  }
});

const productIds = new Set<string>();
for (const prod of products) {
  if (!typeIds.has(prod.type)) throw new Error(`Unknown product type "${prod.type}"`);
  const size = prod.byWeight ? 'per-kg' : `${prod.pack ?? 1}x${prod.size}${prod.unit}`;
  const id = `seed-${slug(`${prod.brand ?? ''} ${prod.name} ${size}`)}`;
  if (productIds.has(id)) throw new Error(`Duplicate product id ${id}`);
  productIds.add(id);
  lines.push(
    `INSERT INTO products (id, product_type_id, name, brand, size_value, size_unit, pack_count, sold_by_weight, is_store_brand, created_at) VALUES (${[
      id,
      prod.type,
      prod.name,
      prod.brand,
      prod.size,
      prod.unit,
      prod.pack ?? 1,
      prod.byWeight ?? false,
      false,
      0,
    ]
      .map(sql)
      .join(', ')});`,
  );
}

const out = join(import.meta.dirname, '../migrations/0005_seed_catalogue.sql');
writeFileSync(out, lines.join('\n--> statement-breakpoint\n') + '\n');
console.log(
  `Wrote ${chains.length} chains, ${categories.length} categories, ${typeIds.size} types, ${productIds.size} products to ${out}`,
);
